//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.DataProvider.DataOperator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_cmaEntities : DbContext
    {
        public db_cmaEntities()
            : base("name=db_cmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_message> tb_message { get; set; }
        public DbSet<tb_user> tb_user { get; set; }
        public DbSet<tb_role> tb_role { get; set; }
        public DbSet<tb_action> tb_action { get; set; }
        public DbSet<tb_monitoritem> tb_monitoritem { get; set; }
        public DbSet<tb_collector> tb_collector { get; set; }
    }
}
