//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.DataProvider.DataOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_monitoritem
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public string Note { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string Paramter { get; set; }
        public string CollectorHost { get; set; }
    }
}
