//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.DataProvider.DataOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_role
    {
        public tb_role()
        {
            this.tb_user = new HashSet<tb_user>();
            this.tb_action = new HashSet<tb_action>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string cFree { get; set; }
        public Nullable<int> iFree { get; set; }
    
        public virtual ICollection<tb_user> tb_user { get; set; }
        public virtual ICollection<tb_action> tb_action { get; set; }
    }
}
