//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.DataProvider.DataOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public tb_user()
        {
            this.tb_role = new HashSet<tb_role>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
        public string Telphone { get; set; }
        public string Email { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual ICollection<tb_role> tb_role { get; set; }
    }
}
